export const pages = [
    {
        pageName:"Home",
        pagePath:"/",
    },
    {
        pageName:"Products",
        pagePath:"/product",
        products:[
            {
                productName:"clothes",
                productPath:"/clothes"
            },
            {
                productName:"clothes1",
                productPath:"/clothes"
            },
            {
                productName:"clothes2",
                productPath:"/clothes"
            }
        ]
    },
    {
        pageName:"About Us",
        pagePath:"/about",
    },
    {
        pageName:"Contact",
        pagePath:"/contact",
    },
]